export default {
  stagesRu: [
    {
      title: 'Этап 1',
      period: 'Декабрь-Февраль, 2023',
      steps: [
        'Разработка концепции и брендбука проекта',
        'Разработка архитектуры платформы',
        'Создание новой версии сайта (дизайн, верстка, мобильная адаптация, разработка ядра личного кабинета)',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage1.svg'),
      },
    },
    {
      title: 'Этап 2',
      period: 'Март-Июнь, 2023',
      steps: [
        'Старт разработки MVP платформы',
        'Разработка маркетингового плана',
        'Запуск группы Market индексов (9 индексов)',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage2.svg'),
      },
    },
    {
      title: 'Этап 3',
      period: 'Июль-Ноябрь, 2023',
      steps: [
        'Старт первичной маркетинговой компании',
        'Тестирование алгоритмов индексов',
        'Тестирование функционала MVP платформы',
        'Прохождение аудита платформы',
        'Запуск глобальной маркетинговой компании ALGA',
        'Запуск Fan индексов (3 индекса)',
        'Запуск MVP платформы ALGA',
        'Разработка мобильного приложения',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage3.svg'),
      },
    },
    {
      title: 'Этап 4',
      period: 'Декабрь 2023-Февраль 2024',
      steps: [
        'Обновление функциональности платформы ALGA с интеграцией собственного бэктестера индексов',
        'Запуск программы с добавлением индексовот адвайзеров платформы',
        'Разработка и включение бэктестера для создания собственных индексов',
        'Проведение IEO на CEX',
        'Регистрация компании и получение правовых документов',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage4.svg'),
      },
    },
    {
      title: 'Этап 5',
      period: 'Март-Июнь, 2024',
      steps: [
        'Партнёрство с другими CEX биржами',
        'Разработка социальной сети для возможности делиться собственными индексами с дальнейшим подключением к ним',
        'Старт разработки собственной индексной биржи',
        'Увеличение количества индексов до 35',
        'Запуск собственного токена, с проведением IEO на CEX',
        'Разработка усилинного алгоритма работы индексов',
        'Разработка публичного REST API',
        'Подготовка механизма тикеров для работы с CEX',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage5.svg'),
      },
    },
    {
      title: 'Этап 6',
      period: 'Июль-Сентябрь, 2024',
      steps: [
        'Публикация тикеров индексов на CEX',
        'Разработка модуля баланса личного кабинета',
        'Разработка Light - режима интерфейса пользователя',
        'Разработка PRO - режима интерфейса пользователя',
        'Разработка функции отложенного исполнения ордера',
        'Разработка функции стоп-лосс ордера',
        'Разработка новой публичной лендинг страницы',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage6.svg'),
      },
    },
    {
      title: 'Этап 7',
      period: 'Октябрь-Декабрь, 2024',
      steps: [
        'Разработка социального модуля',
        'Разработка модуля формирования собственного индекса',
        'Раширение механизмов ввода/вывода новыми способами',
        'Внедрение новых типов индексов до 15 штук',
        'Разработка нового профиля пользователя',
        'Внедрение механизма KYC',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage7.svg'),
      },
    },
    {
      title: 'Этап 8',
      period: 'Январь-Июнь, 2025',
      steps: [
        'Публикация тикеров индексов на новых CEX',
        'Разработка функций биржевой торговли',
        'Разработка публичного REST API с поддержкой Socket API',
        'Разработка модуля Кошелек',
        'Внедрение новых типов индексов до 15 штук и до 5 новых категорий индексов',
        'Интеграция аппаратных хранилищ криптоактивов',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage8.svg'),
      },
    },
  ],
  stagesEn: [
    {
      title: 'Stage 1',
      period: 'December-February, 2023',
      steps: [
        'Development of the concept and brand book of the project',
        'Platform architecture development',
        'Website new version creation and content (design, layout, mobile adaptation, development of the user account core)',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage1.svg'),
      },
    },
    {
      title: 'Stage 2',
      period: 'March-June, 2023',
      steps: [
        'Development of platform MVP',
        'Development of the marketing plan',
        'Launch of the Market Index group (9 index)',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage2.svg'),
      },
    },
    {
      title: 'Stage 3',
      period: 'July-November, 2023',
      steps: [
        'Start of the preliminary marketing campaign',
        'Testing index algorithms',
        'Testing the functionality of the MVP platform',
        'Platform security audit completion',
        'Launch of global marketing company ALGA',
        'Adding Fan Indexes (3)',
        'Launch of MVP of the ALGA platform',
        'Start of Mobile Application Development',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage3.svg'),
      },
    },
    {
      title: 'Stage 4',
      period: 'December 2023 -February 2024',
      steps: [
        'Update the functionality of the ALGA platform with the integration of our own index backtester',
        'Launching a program with the addition of influencer indexes',
        'Development and inclusion of a backtester for creating your own indexes',
        'Conducting an IEO at CEX',
        'Registration of a company and obtaining legal documents',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage4.svg'),
      },
    },
    {
      title: 'Stage 5',
      period: 'March - June, 2024',
      steps: [
        'Partnership with CEX exchanges',
        'Development of a social network for the ability to share your own indexes with further connection to them',
        'Start of development of your own index exchange',
        'Increasing indexes to 35',
        'Launch of own token via IEO on CEX',
        'Enhancing index algorithms',
        'Developing a public REST API',
        'Preparing ticker mechanisms for CEX integration',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage5.svg'),
      },
    },
    {
      title: 'Stage 6',
      period: 'July-September, 2024',
      steps: [
        'Publishing index tickers on CEX',
        'Building a personal account balance module',
        'Creating Light and PRO user interface modes',
        'Adding order execution delay and stop-loss order functions',
        'Designing a new public landing page',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage6.svg'),
      },
    },
    {
      title: 'Stage 7',
      period: 'October-December, 2024',
      steps: [
        'Developing a social module',
        'Crafting a custom index module',
        'Expanding input/output methods',
        'Introducing up to 15 new index types',
        'Updating user profiles',
        'Implementing Know Your Customer (KYC)',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage7.svg'),
      },
    },
    {
      title: 'Stage 8',
      period: 'January-June, 2025',
      steps: [
        'Expanding index ticker publication to new CEXs',
        'Implementing exchange trading features',
        'Enhancing the public REST API with Socket API support',
        'Introducing a Wallet module',
        'Integrating up to 15 new index types and 5 new index categories',
        'Integrating hardware crypto asset storage',
      ],
      icon: {
        width: '101',
        height: '108',
        path: require('./assets/stage8.svg'),
      },
    },
  ],
};
